# Creating a Dockerfile for running a redis server

# Pulling the base image
FROM alpine

# Installing redis
RUN apk add --update redis

# Running the redis server
CMD ["redis-server"]

# Building the image
# docker build -t docker-redis .

# Running the image
# docker run docker-redis

